server:
  port: 9192
spring:
  cloud:
    config:
      enabled: false
  sleuth:
    integration:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: order-service

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment